### ISSUE TITLE
Is NextPy copying your code base under a different name?!

### ISSUE THREAD

**Issue by ibehnam** [pynecone-io/pynecone-chat#30]
I opened an issue here: https://github.com/dot-agent/nextpy/issues/149

NextPy is much younger than Reflex. Their code base is very similar to yours.

**Comment by Alek99** [comment]
Yes, they forked Reflex and copied a large chunk of the code base. But we are moving at an extremely fast velocity and the code that they forked is much older. Since then we have made a bunch of performance and UI improvements. 


They may be in violation of the apache 2 license as seen below in the Notice , Contribution attribution, State changes. We may take legal action on this have not decided yet. 

```
The Apache 2.0 license allows for the use, distribution, and modification of the source code, even for commercial purposes. However, it does have some conditions that protect the original author:

Notice: The original copyright notice and disclaimer must be preserved in all copies or substantial portions of the software. This means that even if someone changes the name of the project, they still need to give credit to the original author.

Contribution attribution: If they modify the code and then distribute it, they must include a notice that they changed the files. This helps track what changes were made by whom.

State changes: If they modify your code, they must include a prominent notice stating that they changed the code and include the date of any change.

So, while someone can copy the source code and change the name, they cannot do so without giving credit to the original author as per the conditions of the Apache 2.0 license

```

**Comment by anubrag** [comment]
![reflex vs nextpy](https://github.com/reflex-dev/reflex-chat/assets/25473195/62f4be39-5990-4ffe-8eb8-bb1de2960d7e)
